# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74111479495344e8e9ea913baf1b17654c3b6b64ddbd006e553b692a46ca1e3ee0960b6a3154d2f77f53d659fe40de000a90ce68f36f4c81eafe26a8cb5a2100

test:
  secret_key_base: 4119ec880f4ce6611129c1978405698d92b0ea1c1838a4f66db46d038c761a63c7b26a71c0c9d4872e6dca9130a2f745a15f28fc13db200cd7ded69bcf3adb5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
