# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a61adb40532d0c3de479519f4582bc88382824b99a1c92b70563d54633a9c3b0659522dadf5088f9fbdf2b0b624fd9540fc6fc933df2d4d14288be731d99a953

test:
  secret_key_base: a2a4fa70ea9cdb028b6ad0dbc9e8243629fd8ddc3dc4d6375476bc0b1f9b52db6d2bf2512bccda84c8f13e634e655058d8e6846518fa24b1cf48936eb8fcdcde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
